version: '3.7'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_HOST: localhost
      POSTGRES_DB: dev
    volumes:
      - db:/var/lib/postgresql/data
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8081:8080
  server:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - default
    ports:
      - '8080:8080'
    links:
      - db
volumes:
  db:
